name: Docker Image Build Check

on:
  push:
    branches-ignore:
      - master

jobs:
  build-main-images:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          ### Rabbitmq 3.7.14
          - image: '3.7.14/Dockerfile'
            tags: [ "spryker/rabbitmq:3.7.14" ]
            platform: [ "linux/amd64" ]

          ### Rabbitmq 3.8
          - image: '3.8/Dockerfile'
            tags: [ "spryker/rabbitmq:3.8" ]
            platform: [ "linux/amd64", "linux/arm64" ]

          ### Rabbitmq 3.9
          - image: '3.9/Dockerfile'
            tags: [ "spryker/rabbitmq:3.9" ]
            platform: [ "linux/amd64", "linux/arm64" ]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          file: ${{ matrix.image }}
          tags: ${{ join(matrix.tags) }}
          platforms: ${{ join(matrix.platform) }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}

  build-child-images:
    needs: build-main-images
    runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          include:
            ### Rabbitmq 3.7.14-amqp1
            - image: '3.7.14/amqp1/Dockerfile'
              tags: [ "spryker/rabbitmq:3.7.14-amqp1" ]
              platform: [ "linux/amd64" ]

            ### Rabbitmq 3.7.14-shovel
            - image: '3.7.14/shovel/Dockerfile'
              tags: [ "spryker/rabbitmq:3.7.14-shovel" ]
              platform: [ "linux/amd64" ]

            ### Rabbitmq 3.8-amqp1
            - image: '3.8/amqp1/Dockerfile'
              tags: [ "spryker/rabbitmq:3.8-amqp1" ]
              platform: [ "linux/amd64", "linux/arm64" ]

            ### Rabbitmq 3.8-shovel
            - image: '3.8/shovel/Dockerfile'
              tags: [ "spryker/rabbitmq:3.8-shovel" ]
              platform: [ "linux/amd64", "linux/arm64" ]

            ### Rabbitmq 3.9-amqp1
            - image: '3.9/amqp1/Dockerfile'
              tags: [ "spryker/rabbitmq:3.9-amqp1" ]
              platform: [ "linux/amd64", "linux/arm64" ]

            ### Rabbitmq 3.9-shovel
            - image: '3.9/shovel/Dockerfile'
              tags: [ "zyuzka/rabbitmq:3.9-shovel" ]
              platform: [ "linux/amd64", "linux/arm64" ]

      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: false
            file: ${{ matrix.image }}
            tags: ${{ join(matrix.tags) }}
            platforms: ${{ join(matrix.platform) }}
            secrets: |
              GIT_AUTH_TOKEN=${{ secrets.GIT_AUTH_TOKEN }}
