name: CI/CD RabbitMQ Build and Scan

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-scan-images-for-vulnerabilities:
    strategy:
      fail-fast: false
      matrix:
        include:
          # RabbitMQ 4.1 variants
          - image: "4.1/Dockerfile"
            tag: "spryker/rabbitmq:4.1"
            platforms: "linux/amd64,linux/arm64"
          - image: "4.1/amqp1/Dockerfile"
            tag: "spryker/rabbitmq:4.1-amqp1"
            platforms: "linux/amd64,linux/arm64"
          - image: "4.1/shovel/Dockerfile"
            tag: "spryker/rabbitmq:4.1-shovel"
            platforms: "linux/amd64,linux/arm64"

          # RabbitMQ 4.2 variants
          - image: "4.2/Dockerfile"
            tag: "spryker/rabbitmq:latest"
          - image: "4.2/Dockerfile"
            tag: "spryker/rabbitmq:4.2"
            platforms: "linux/amd64,linux/arm64"
          - image: "4.2/amqp1/Dockerfile"
            tag: "spryker/rabbitmq:4.2-amqp1"
            platforms: "linux/amd64,linux/arm64"
          - image: "4.2/shovel/Dockerfile"
            tag: "spryker/rabbitmq:4.2-shovel"
            platforms: "linux/amd64,linux/arm64"

    name: Build and Scan - ${{ matrix.tag }}
    uses: spryker-projects/gha-reusable-workflows/.github/workflows/ci.yml@main
    with:
      image: ${{ matrix.image }}
      tag: ${{ matrix.tag }}
      platforms: ${{ matrix.platforms }}
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.WEBHOOK_CE_RELEASE_IMAGES_RABBITMQ }}
